### ISSUE TITLE
how to fix "No matching distribution found for http.server"?

### ISSUE THREAD

**Issue by luckypoem** [luxrck/nut#1]
hi.

git clone https://github.com/luxrck/nut/
cd nut
python setup.py install

root@wh:~/nut# which nut
/usr/local/bin/nut
root@wh:~/nut# nut -h
Traceback (most recent call last):
  File "/usr/local/bin/nut", line 9, in <module>
    load_entry_point('nut==0.0.1', 'console_scripts', 'nut')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/nut-0.0.1-py2.7.egg/nut/__main__.py", line 4, in <module>
    from .cmd import *
  File "/usr/local/lib/python2.7/dist-packages/nut-0.0.1-py2.7.egg/nut/cmd.py", line 3, in <module>
    from http.server import HTTPServer, SimpleHTTPRequestHandler
ImportError: No module named http.server
root@wh:~/nut# which pip 
/usr/local/bin/pip
root@wh:~/nut# pip install http.server
Collecting http.server
  Could not find a version that satisfies the requirement http.server (from versions: )
No matching distribution found for http.server
root@wh:~/nut#

tks

**Comment by luxrck** [comment]
Sorry, please use python3 instead.

**Comment by luckypoem** [comment]
hi.
我装了python3,然后，
root@wh:~/nut-blog# nut build
Traceback (most recent call last):
  File "/usr/local/bin/nut", line 11, in <module>
    load_entry_point('nut==0.0.1', 'console_scripts', 'nut')()
  File "/usr/local/lib/python3.6/dist-packages/nut-0.0.1-py3.6.egg/nut/__main__.py", line 19, in main
    build(".")
  File "/usr/local/lib/python3.6/dist-packages/nut-0.0.1-py3.6.egg/nut/cmd.py", line 25, in build
    return Generator(root).generate()
  File "/usr/local/lib/python3.6/dist-packages/nut-0.0.1-py3.6.egg/nut/generator.py", line 25, in __init__
    self.reload()
  File "/usr/local/lib/python3.6/dist-packages/nut-0.0.1-py3.6.egg/nut/generator.py", line 74, in reload
    load_articles(articles_dir, [self.categories])
  File "/usr/local/lib/python3.6/dist-packages/nut-0.0.1-py3.6.egg/nut/generator.py", line 53, in load_articles
    a = article(location)
  File "/usr/local/lib/python3.6/dist-packages/nut-0.0.1-py3.6.egg/nut/processor.py", line 90, in article
    a.header = header(source, location)
  File "/usr/local/lib/python3.6/dist-packages/nut-0.0.1-py3.6.egg/nut/processor.py", line 72, in header
    h.date = datetime.strptime(value, c.datetime_format)
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-12-04 16:43:20' does not match format '%Y-%m-%d %H:%M %Z%z'

怎么解决错误-
ValueError: time data '2018-12-04 16:43:20' does not match format '%Y-%m-%d %H:%M %Z%z'？
thank you.

**Comment by luxrck** [comment]
打开config.yml，把`datetime_format`改为`%Y-%m-%d %H:%M:%S`.
